version: "3.9"

services:
  wordpress:
    build: .
    volumes:
      - wordpress:/var/www/html
      - ./:/var/www/html/wp-content/plugins/galoy-for-woocommerce
    ports:
      - "8080:80"
    restart: on-failure:10
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_pwd
    depends_on:
      - db

  db:
    image: mysql:8.3
    volumes:
      - db:/var/lib/mysql
    restart: on-failure:10
    environment:
      MYSQL_ROOT_PASSWORD: rootpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_pwd

volumes:
  db:
  wordpress:
